// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdUjcU84M82Fzh58H5i7Imdv0UIb6JfM',
    appId: '1:461049299837:web:affa627e6a354c3fb04214',
    messagingSenderId: '461049299837',
    projectId: 'lesson-3---flutter',
    authDomain: 'lesson-3---flutter.firebaseapp.com',
    storageBucket: 'lesson-3---flutter.appspot.com',
    measurementId: 'G-2ECHCTWY5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoI1c5UhkfkztNhghVfRPWs9LUc7EomCc',
    appId: '1:461049299837:android:423082036c53f38fb04214',
    messagingSenderId: '461049299837',
    projectId: 'lesson-3---flutter',
    storageBucket: 'lesson-3---flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChk-MPQaZd4qRGbStihm5FRP9tZ9So07Q',
    appId: '1:461049299837:ios:cf9328ffc96284e1b04214',
    messagingSenderId: '461049299837',
    projectId: 'lesson-3---flutter',
    storageBucket: 'lesson-3---flutter.appspot.com',
    iosBundleId: 'com.example.lesson3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChk-MPQaZd4qRGbStihm5FRP9tZ9So07Q',
    appId: '1:461049299837:ios:65b387dab41a53d9b04214',
    messagingSenderId: '461049299837',
    projectId: 'lesson-3---flutter',
    storageBucket: 'lesson-3---flutter.appspot.com',
    iosBundleId: 'com.example.lesson3.RunnerTests',
  );
}
